# Generated by Django 3.2 on 2021-04-26 11:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='lat',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='long',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='8961502938', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
